<?php
enum AuthExeption: string
{
    case SUCCESS_CONNECION = 'SUCCESSFULLY';
    case INVALID_PASSWORD = 'INVALID_PASSWORD';
    case INVALID_INPUT = 'INVALID_INPUT';
    case INVALID_EMAIL = 'INVALID_EMAIL';
    case NOT_FOUND_EMAIL = 'NOT_FOUND_EMAIL';
    case WEAK_PASSWORD = 'WEAK_PASSWORD';
    case EMAIL_EXISTS = 'EMAIL_EXISTS';
    case NOT_MATCH_PASSWORD = 'NOT_MATCH_PASSWORD';
    case FAIL = 'FAIL';

}
